version: '3.8'

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_API_KEY=dev-api-key
    volumes:
      - ./seq-data:/data
    restart: unless-stopped
